### ISSUE TITLE
Skip MergeNativeLibsTask when there are no native libs

### ISSUE THREAD

**Issue by CristianGM** [gradle/android-cache-fix-gradle-plugin#90] opened 2020-05-18 21:16 UTC
Basically what Google will do eventually
https://issuetracker.google.com/issues/154984238

Is it possible to do it from this plugin?

**Comment by runningcode** [comment] 2020-06-11 08:36
Look like Google added the `@SkipWhenEmpty` annotation to some of the inputs:
```
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    @get:SkipWhenEmpty
    abstract val projectNativeLibs: ConfigurableFileCollection

    @get:Classpath
    @get:SkipWhenEmpty
    abstract val subProjectNativeLibs: ConfigurableFileCollection

    @get:Classpath
    @get:SkipWhenEmpty
    abstract val externalLibNativeLibs: ConfigurableFileCollection
```

That being said, it looks like this fix isn't working since the task is still being run on AGP 4.1.0-beta01.

@CristianGM how long does this task take to run on your build?

**Comment by crgarridos** [comment] 2020-06-18 10:17
Hi, @runningcode. For example, in our project we have more than 200 modules, the cumulate time of this task doing "nothing" takes on average 15 minutes 😬

**Comment by runningcode** [comment] 2020-07-06 09:42
@crgarridos it is very likely that one of your third party dependencies includes a native library therefore this task is merging those native libraries.
A common one in Android project's is Facebook Flipper which includes native libraries.
Can you double check that none of your dependencies include native libraries?

**Comment by crgarridos** [comment] 2020-07-15 11:25
Oh, we do actually have flipper and it is in the deep bottom of our dependency graph, I'll check this out and come back to confirm.

**Comment by runningcode** [comment] 2020-08-06 11:29
I will close this issue assuming that this is being caused by flipper pulling in native libraries. Feel free to re-open if this is not the case.

**Closed by runningcode** 2020-08-06 11:29 UTC
